<a href="https://colab.research.google.com/github/kartikdhoke9923/Ai-and-dl/blob/main/ainn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
df=pd.read_csv("insurance_data.csv")

In [19]:
df.head()

,age,affordibility,bought_insurance
0,22,1,0
1,25,0,0
2,47,1,1
3,52,0,0
4,46,1,1


In [20]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(df[['age','affordibility']],
                                                           df.bought_insurance, test_size=0.2, random_state=25)

In [21]:
# df.bought_insurance

In [22]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

In [23]:
model = keras.Sequential([
  keras.layers.Dense(1,input_shape=(2,),activation = 'sigmoid',
  kernel_initializer='ones',bias_initializer='zeros'),
  keras.layers.Dense(1,input_shape=(2,),activation = 'relu',
  kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=1000)

Epoch 1/1000


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7092
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7051
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.7031
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.7012
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.5000 - loss: 0.6992
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.6973
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.5000 - loss: 0.6954
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.5000 - loss: 0.6936
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6918
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5000 - lo

In [24]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - accuracy: 0.6667 - loss: 0.5256


[0.5255629420280457, 0.6666666865348816]

In [25]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step


array([[0.6448798 ],
       [0.52862585],
       [0.27196255],
       [0.5716721 ],
       [0.6518911 ],
       [0.6911237 ]], dtype=float32)

In [26]:
y_test

,bought_insurance
2,1
10,0
21,0
11,0
14,1
9,1


In [31]:
coef = model.get_weights()

In [33]:
coef

[array([[1.7302071],
        [1.0453434]], dtype=float32),
 array([-0.62165046], dtype=float32),
 array([[1.1731899]], dtype=float32),
 array([-0.26436844], dtype=float32)]